// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRUxwy1VhCdRYDW3SXhenHTgLUtMMqYE',
    appId: '1:254075851666:web:0806f86fea4f9786d8e74b',
    messagingSenderId: '254075851666',
    projectId: 'projeto-integrador-4-4dcf0',
    authDomain: 'projeto-integrador-4-4dcf0.firebaseapp.com',
    storageBucket: 'projeto-integrador-4-4dcf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqICiUoBxJvQ49HPYfEq8qF8U0JpUrq7I',
    appId: '1:254075851666:android:d4c0045429fbcba3d8e74b',
    messagingSenderId: '254075851666',
    projectId: 'projeto-integrador-4-4dcf0',
    storageBucket: 'projeto-integrador-4-4dcf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMqQRGLzrZdBj94ERpyhUJNPnBfS6xkCQ',
    appId: '1:254075851666:ios:0f989404d0e5f15ed8e74b',
    messagingSenderId: '254075851666',
    projectId: 'projeto-integrador-4-4dcf0',
    storageBucket: 'projeto-integrador-4-4dcf0.appspot.com',
    iosBundleId: 'com.example.projetoIntegrador4',
  );
}